FROM python:3.12-slim

WORKDIR /bot

# Устанавливаем зависимости для psycopg2
RUN apt-get update && apt-get install -y \
    curl \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*


# Копируем requirements.txt из папки src
COPY src/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY .env .
COPY src/ ./src/


ENV PYTHONPATH=/bot
# Команда запуска указана в docker-compose для поддержки --reload

