"""favorite_and_discount_models

Revision ID: 19c9282158a8
Revises: bcf9dfccbb24
Create Date: 2025-03-10 21:40:19.740154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19c9282158a8'
down_revision: Union[str, None] = 'bcf9dfccbb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_info', sa.Text(), nullable=False),
    sa.Column('about_company', sa.Text(), nullable=False),
    sa.Column('contacts', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('favoritefirework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('firework_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firework_id'], ['firework.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'firework_id', name='unique_favorite')
    )
    op.create_table('fireworkdiscount',
    sa.Column('firework_id', sa.Integer(), nullable=False),
    sa.Column('discount_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firework_id'], ['firework.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('firework_id', 'discount_id')
    )
    op.create_unique_constraint(None, 'address', ['id'])
    op.create_unique_constraint(None, 'cart', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'firework', ['id'])
    op.create_unique_constraint(None, 'firework_media', ['id'])
    op.create_unique_constraint(None, 'firework_tag', ['id'])
    op.create_unique_constraint(None, 'media', ['id'])
    op.create_unique_constraint(None, 'order', ['id'])
    op.create_unique_constraint(None, 'orderfirework', ['id'])
    op.create_unique_constraint(None, 'orderstatus', ['id'])
    op.create_unique_constraint(None, 'tag', ['id'])
    op.add_column('user', sa.Column('age_verified', sa.Boolean(), nullable=False))
    op.drop_column('user', 'age_verifid')
    op.create_unique_constraint(None, 'useraddress', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useraddress', type_='unique')
    op.add_column('user', sa.Column('age_verifid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'age_verified')
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_constraint(None, 'orderstatus', type_='unique')
    op.drop_constraint(None, 'orderfirework', type_='unique')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'media', type_='unique')
    op.drop_constraint(None, 'firework_tag', type_='unique')
    op.drop_constraint(None, 'firework_media', type_='unique')
    op.drop_constraint(None, 'firework', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_constraint(None, 'address', type_='unique')
    op.drop_table('fireworkdiscount')
    op.drop_table('favoritefirework')
    op.drop_table('discount')
    op.drop_table('botinfo')
    # ### end Alembic commands ###
