"""no_discription_please_rename

Revision ID: 2026
Revises: 01
Create Date: 2025-03-26 16:27:56.840757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026'
down_revision: Union[str, None] = '01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'address', ['id'])
    op.create_unique_constraint(None, 'botinfo', ['id'])
    op.create_unique_constraint(None, 'cart', ['id'])
    op.create_unique_constraint(None, 'discount', ['id'])
    op.create_unique_constraint(None, 'favoritefirework', ['id'])
    op.create_unique_constraint(None, 'firework', ['id'])
    op.drop_column('firework', 'tags')
    op.drop_column('firework', 'manufacturer')
    op.create_unique_constraint(None, 'firework_media', ['id'])
    op.create_unique_constraint(None, 'firework_tag', ['id'])
    op.create_unique_constraint(None, 'media', ['id'])
    op.create_unique_constraint(None, 'order', ['id'])
    op.create_unique_constraint(None, 'orderfirework', ['id'])
    op.create_unique_constraint(None, 'orderstatus', ['id'])
    op.create_unique_constraint(None, 'tag', ['id'])
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'useraddress', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useraddress', type_='unique')
    op.drop_column('user', 'birth_date')
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_constraint(None, 'orderstatus', type_='unique')
    op.drop_constraint(None, 'orderfirework', type_='unique')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'media', type_='unique')
    op.drop_constraint(None, 'firework_tag', type_='unique')
    op.drop_constraint(None, 'firework_media', type_='unique')
    op.add_column('firework', sa.Column('manufacturer', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('firework', sa.Column('tags', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'firework', type_='unique')
    op.drop_constraint(None, 'favoritefirework', type_='unique')
    op.drop_constraint(None, 'discount', type_='unique')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_constraint(None, 'botinfo', type_='unique')
    op.drop_constraint(None, 'address', type_='unique')
    # ### end Alembic commands ###
