"""user_model_adjusted_bot_message_added

Revision ID: ca3e37c82c99
Revises: 19c9282158a8
Create Date: 2025-03-11 15:04:08.257595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca3e37c82c99'
down_revision: Union[str, None] = '19c9282158a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'botinfo', ['id'])
    op.create_unique_constraint(None, 'discount', ['id'])
    op.create_unique_constraint(None, 'favoritefirework', ['id'])
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('user', 'prefered_language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prefered_language', postgresql.ENUM('EN', 'RU', name='preferedlanguage'), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'hashed_password')
    op.drop_constraint(None, 'favoritefirework', type_='unique')
    op.drop_constraint(None, 'discount', type_='unique')
    op.drop_constraint(None, 'botinfo', type_='unique')
    # ### end Alembic commands ###
