"""init

Revision ID: 01
Revises:
Create Date: 2025-03-15 23:37:19.395634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('price_per_unit', sa.Float(), nullable=False))
    op.add_column('firework', sa.Column('code', sa.String(), nullable=False))
    op.add_column('firework', sa.Column('measurement_unit', sa.String(), nullable=False))
    op.add_column('firework', sa.Column('charges_count', sa.Integer(), nullable=True))
    op.add_column('firework', sa.Column('effects_count', sa.Integer(), nullable=True))
    op.add_column('firework', sa.Column('product_size', sa.String(), nullable=False))
    op.add_column('firework', sa.Column('packing_material', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'firework', ['product_size'])
    op.create_unique_constraint(None, 'firework', ['code'])
    op.alter_column('orderfirework', 'price_per_unit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orderfirework', 'price_per_unit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'firework', type_='unique')
    op.drop_constraint(None, 'firework', type_='unique')
    op.drop_column('firework', 'packing_material')
    op.drop_column('firework', 'product_size')
    op.drop_column('firework', 'effects_count')
    op.drop_column('firework', 'charges_count')
    op.drop_column('firework', 'measurement_unit')
    op.drop_column('firework', 'code')
    op.drop_column('cart', 'price_per_unit')
    # ### end Alembic commands ###
